# Generated by Django 3.1.4 on 2021-01-12 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20210112_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
    ]
