# Generated by Django 3.1.4 on 2021-01-13 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20210112_1350'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topping',
            new_name='Entry',
        ),
    ]
